version: "3.5"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - mynet

  server-prod:
    image: server-prod
    build:
      context: ./server/
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./mobile-builds:/app/mobile-builds
    depends_on:
      - db
    networks:
      - mynet

  nextjs-prod:
    image: nextjs-prod
    build:
      context: ./web/
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - shared_volume:/app/public/mobile
    ports:
      - 8081:8081
    networks:
      - mynet

  nginx-prod:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - shared_volume:/app/public/mobile
    depends_on:
      - nextjs-prod
      - server-prod
    ports:
      - "80:80"
    networks:
      - mynet

  # mobile:
  #   image: mobile
  #   build:
  #     context: ./mobile/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - shared_volume:/app/public/mobile
  #   networks:
  #     - mynet

  dev-server-prod:
    image: dev-server-prod
    build:
      context: ./dev-server/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8083:8083"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  db_data:
  shared_volume: