name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID_GITHUB: ${{ secrets.CLIENT_ID_GITHUB }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      MICROSOFT_TENANT_ID: ${{ secrets.MICROSOFT_TENANT_ID }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      LOCAL_API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./mobile

      - name: Create .env file
        run: |
          cat > mobile/.env << EOF
          CLIENT_ID_GITHUB=${{ secrets.CLIENT_ID_GITHUB }}
          DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
          MICROSOFT_CLIENT_ID=${{ secrets.MICROSOFT_CLIENT_ID }}
          MICROSOFT_TENANT_ID=${{ secrets.MICROSOFT_TENANT_ID }}
          API_BASE_URL=${{ secrets.API_BASE_URL }}
          LOCAL_API_BASE_URL=${{ secrets.LOCAL_API_BASE_URL }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }}
          EOF

      - name: Build APK
        run: flutter build apk --release
        working-directory: mobile

      - name: Copy APK to /public
        run: |
          mkdir -p web/public
          cp mobile/build/app/outputs/flutter-apk/app-release.apk web/public/client.apk

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Create new branch
        run: |
          git checkout -b update-client-apk-$(date +%Y%m%d%H%M%S)
          git add web/public/client.apk
          git commit -m "Update client.apk from CI build" || echo "No changes to commit"

      - name: Push changes to new branch
        run: |
          git push origin HEAD
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Update client.apk from CI build"
          branch: update-client-apk
          title: "Automated Update of client.apk"
          body: "This PR was automatically created by GitHub Actions to update the client APK."
